name: VC_P5
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jax==0.7.1
      - jaxlib==0.7.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lap==0.5.12
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - protobuf==4.25.8
      - psutil==7.1.0
      - pycparser==2.23
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - sounddevice==0.5.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tzdata==2025.2
      - ultralytics==8.3.215
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0